services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    env_file:
      - ../../.env.linos
    environment:
      - TZ=${TZ:-Europe/Berlin}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_data:/data

volumes:
  caddy_config:
  caddy_data:
