services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf

