version: "3.8"

services:
  service-index:
    image: nginx:alpine
    container_name: service-index
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "8081:80"   # Seite erreichbar unter http://<host>:8081
    restart: unless-stopped
